sonar.projectKey=diego615_alpha-beta-lab
sonar.organization=diego615

sonar.projectName=alpha-beta-lab

sonar.sources=src
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
